Repository hmcts/nfdiv-case-orchestration-service, pull requests merged in 2021-01, with the labels that each got.

#10 NFDIV-325 Get user details from ID token
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/AuthenticateRespondentTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/IntegrationTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/model/idam/UserDetails.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamUtils.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/UserDetailsConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/OidcUserDetailsProvider.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/UserDetailsProvider.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AuthenticateRespondent.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/util/UserDivorcePartyLookup.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AuthenticateRespondentWorkflow.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/AuthenticateRespondentITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AuthenticateRespondentUTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/AuthenticateRespondentWorkflowUTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-10

#14 switch to use nfdiv-lib
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/IdamUtils.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/UserDetailsConfiguration.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/OidcUserDetailsProvider.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/UserDetails.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/idam/UserDetailsProvider.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AuthenticateRespondentTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/AuthenticateRespondentTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/IdamTestSupport.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveAosCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrieveDraftTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/RetrievePbaNumbersITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/AuthenticateRespondentTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/GetCaseWithIdWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-14

#15 Use nfdiv-common-lib removeAllPetitionDocuments
  build.gradle
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveMiniPetitionDraftDocumentsTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/ProcessPbaPaymentAbstractITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveMiniPetitionDraftDocumentsTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-15

#16 Use nfdiv-common-lib removeAllDocumentsByType
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveCertificateOfEntitlementDocumentsTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveCostOrderDocumentTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveDecreeNisiDocumentTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveCertificateOfEntitlementDocumentsTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveCostOrderDocumentTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/RemoveDecreeNisiDocumentTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-16

#18 Use nfdiv-common-lib getDaCaseData
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDaCaseDataTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitDaCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDaCaseDataTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-18

#20 Use nfdiv-common-lib getDnClarificationCaseData and getDnCaseData
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseDataTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitDnCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToDnCaseDataTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-20

#17 Use nfdiv-common-lib getAosCaseData
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToAosCaseDataTask.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitCoRespondentAosCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/SubmitRespondentAosCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/FormatDivorceSessionToAosCaseDataTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-17

#21 modify gradle tasks to load secrets from azure cli
  README.md
  build.gradle
  charts/nfdiv-cos/Chart.yaml
  charts/nfdiv-cos/values.yaml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java
  src/integrationTest/resources/application-aat.properties
  src/integrationTest/resources/application-saat.properties
  src/integrationTest/resources/application.properties
  src/integrationTest/resources/example-application-local.properties
  src/main/resources/application.yml
  src/main/resources/example-application-aat.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-21

#7 Set nfdiv_cos service name
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  build.gradle
  charts/nfdiv-cos/Chart.yaml
  charts/nfdiv-cos/values.preview.template.yaml
  charts/nfdiv-cos/values.yaml
  src/contractTest/resources/application.yml
  src/integrationTest/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-7

#28 Upstream test with ccd pr
  build.gradle
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/EditBulkCaseListingTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/callback/nightly/pipeline/RemoveCaseFromListingTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/support/cos/CosApiClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/document/template/DocumentType.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoECoRespondentCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentSolicitorLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CostOrderCoRespondentCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CostOrderCoRespondentSolicitorCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentSolicitorCoverLetterGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceOrderGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceRefusalOrderTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DispensedServiceRefusalOrderTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/OrderToDispenseGenerationTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ListForPronouncementDocGenerationWorkflow.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/BulkCaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/document/template/DocumentTypeTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/EditBulkCaseITest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/functionaltest/callback/CourtOrderDocumentsUpdateCallbackTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CourtOrderDocumentsUpdateServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CostOrderCoRespondentSolicitorCoverLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/BasePayloadSpecificDocumentGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoECoRespondentCoverLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentCoverLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/CoERespondentSolicitorLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentCoverLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/bulk/printing/DnGrantedRespondentSolicitorCoverLetterGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/AbstractGeneralOrderGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/generalorders/GeneralOrderDraftGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceOrderGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DeemedServiceRefusalOrderTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DispensedServiceRefusalOrderDraftTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/DispensedServiceRefusalOrderTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/OrderToDispenseGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceDecisionOrderGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/servicejourney/ServiceRefusalOrderGenerationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/ListForPronouncementDocGenerationWorkflowTest.java
  src/test/resources/jsonExamples/payloads/updateCourtOrderDocuments.json
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-28

#19 Use nfdiv-common-lib transformToDivorceSession
  build.gradle
  charts/nfdiv-cos/Chart.yaml
  charts/nfdiv-cos/values.yaml
  src/contractTest/resources/application.yml
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/HealthCheckITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RetrieveAosCaseITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RetrieveCaseITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RetrieveDraftTest.java
  src/integrationTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseFormatterClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/management/monitoring/health/CaseFormatterServiceHealthCheck.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataDraftToDivorceFormatterTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataToDivorceFormatterTask.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataDraftToDivorceFormatterTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/CaseDataToDivorceFormatterTaskTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-19
