Repository hmcts/nfdiv-case-orchestration-service, pull requests merged in 2021-02, with the labels that each got.

#33 remove draft store related API calls
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/draft/DraftServiceEndToEndTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/cms/CmsClientSupport.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/cos/DraftsSubmissionSupport.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/DeleteDraftTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/RetrieveDraftTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SaveDraftITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/OrchestrationController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseOrchestrationService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DeleteDraftTask.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SaveToDraftStore.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DeleteDraftWorkflow.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RetrieveDraftWorkflow.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SaveDraftWorkflow.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitToCCDWorkflow.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DeleteDraftTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SaveToDraftStoreTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/DeleteDraftTaskWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RetrieveDraftWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SaveDraftWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitToCCDWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-33

#35 Add sourceCompatibility to job-scheduler gradle.build file.
  job-scheduler/build.gradle
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-35

#32 Nfdiv 386 post case endpoint
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/maintenance/SubmitCaseToCCDIntegrationTest.java
  src/functionalTest/resources/application.properties
  src/functionalTest/resources/fixtures/maintenance/submit/draft-divorce-session.json
  src/functionalTest/resources/fixtures/retrieve-aos-case/aos-divorce-session.json
  src/functionalTest/resources/fixtures/retrieve-case/divorce-session.json
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/draftcase/SubmitDraftCaseTest.java
  src/integrationTest/resources/jsonExamples/payloads/transformations/ccd/case-data.json
  src/integrationTest/resources/jsonExamples/payloads/transformations/ccd/draft-case.json
  src/integrationTest/resources/jsonExamples/payloads/transformations/divorce/case-data.json
  src/integrationTest/resources/jsonExamples/payloads/transformations/divorce/draft-case.json
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/draftcase/SubmitDraftCaseToCcd.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDraftCaseToCCDWorkflow.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseOrchestrationServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/draftcase/SubmitDraftCaseToCcdTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/DataTransformationTestHelper.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDraftCaseToCCDWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-32

#36 Fixed functional tests
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/dataextraction/FamilyManDataExtractionIT.java
  src/functionalTest/resources/application.properties
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-36

#37 update deps
  build.gradle
  charts/nfdiv-cos/Chart.yaml
  charts/nfdiv-cos/requirements.yaml
  charts/nfdiv-cos/values.yaml
  job-scheduler/build.gradle
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreateTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DuplicateCaseValidationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ProcessPbaPaymentTaskAbstractTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchCasesDAOverdueTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchDNPronouncedCasesTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshContinueTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/PbaClientErrorTestUtil.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RespondentSolicitorLinkCaseWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-37

#40 Bump chart version
  charts/nfdiv-cos/Chart.yaml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-40

#41 Upgrade again
  build.gradle
  charts/nfdiv-cos/Chart.yaml
  charts/nfdiv-cos/requirements.yaml
  charts/nfdiv-cos/values.yaml
  job-scheduler/build.gradle
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/config/PropertyLogger.java
  src/main/resources/application.yml
  src/main/resources/bootstrap.yaml
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/framework/workflow/RetryableBulkCaseWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/BulkCaseCreateTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/DuplicateCaseValidationTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ProcessPbaPaymentTaskAbstractTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchCasesDAOverdueTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/SearchDNPronouncedCasesTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/WelshContinueTaskTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/testutil/PbaClientErrorTestUtil.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/RespondentSolicitorLinkCaseWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-41

#43 Added get case endpoint to retrieve case from cms
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/GetCaseITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-43

#45 Add functional tests for get case endpoint
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/GetCaseFromCcdTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-45

#46 Remove workflow from case endpoint requests
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/GetCaseFromCcdTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/PatchCaseInCCDTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/PostCaseToCCDTest.java
  src/functionalTest/resources/fixtures/maintenance/patch/patch.json
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/ccdcase/PatchCaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/ccdcase/SubmitDraftCaseTest.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CMSClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseMaintenanceClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ccdcase/PatchCaseInCCD.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ccdcase/SubmitDraftCaseToCcd.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/PatchCaseInCCDWorkflow.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDraftCaseToCCDWorkflow.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ccdcase/PatchCaseInCCDTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/tasks/ccdcase/SubmitDraftCaseToCcdTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/PatchCaseInCCDWorkflowTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/workflows/SubmitDraftCaseToCCDWorkflowTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-46

#48 Invoke CCD directly from COS
  build.gradle
  dependency-check-suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/GetCaseFromCcdTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/GetCaseITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/HealthCheckITest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/IdamTestSupport.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/MockedFunctionalTest.java
  src/integrationTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CMSClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/advice/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/GetCaseResponse.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/domain/model/OrchestrationConstants.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/exception/BaseException.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/exception/DuplicateCaseException.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/TestConstants.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
  src/test/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-48

#50 Fixed missing config for contract tests
  src/contractTest/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-50

#51 Patch case directly to CCD
  src/contractTest/resources/application.yml
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/PatchCaseInCCDTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/context/ServiceContextConfiguration.java
  src/functionalTest/resources/application.properties
  src/functionalTest/resources/fixtures/maintenance/patch/initial-case-for-patch.json
  src/functionalTest/resources/fixtures/maintenance/patch/initial-submit.json
  src/functionalTest/resources/fixtures/maintenance/patch/patch-bad-data.json
  src/functionalTest/resources/fixtures/maintenance/patch/patch-case.json
  src/functionalTest/resources/fixtures/maintenance/patch/patch-no-data.json
  src/functionalTest/resources/fixtures/maintenance/patch/patch-no-id.json
  src/functionalTest/resources/fixtures/maintenance/patch/patch.json
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/ccdcase/PatchCaseTest.java
  src/integrationTest/resources/application.yml
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CMSClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/client/CaseRoleClient.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/advice/GlobalExceptionHandler.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/ccd/CasePatchService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/main/resources/application.yml
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/advice/GlobalExceptionHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/ccd/CasePatchServiceTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
  src/test/resources/application.yml
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-51

#53 Fixed exception handler method argument and test
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/GetCaseITest.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/advice/GlobalExceptionHandler.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-53

#49 Nfdiv 471 prevent duplicate case creation
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/PostCaseToCCDTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/SubmitCCDCaseTest.java
  src/integrationTest/java/uk/gov/hmcts/reform/divorce/orchestration/controller/ccdcase/SubmitDraftCaseTest.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseController.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/exception/CaseAlreadyExistsException.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/CaseService.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/controller/CaseControllerTest.java
  src/test/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImplTest.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-49

#54 Added e2e test for get case filtering amended cases
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/ccdcase/GetCaseFromCcdTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/maintenance/AmendPetitionTest.java
  src/functionalTest/java/uk/gov/hmcts/reform/divorce/support/CcdSubmissionSupport.java
  src/main/java/uk/gov/hmcts/reform/divorce/orchestration/service/impl/CaseServiceImpl.java
Labels: ns:nfdiv, prd:nfdiv, rel:nfdiv-cos-pr-54
